### ISSUE TITLE
plz check this error

### ISSUE THREAD

**Issue by ashrafalzyoud** [nanego/redmine_admin_activity#16]
== 20200331162520 CreateJournalSettings: migrating ============================
-- create_table(:journal_settings)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Column `user_id` on table `journal_settings` does not match column `id` on `users`, which has type `int(11)`. To resolve this issue, change the type of the `user_id` column on `journal_settings` to be :integer. (For example `t.integer :user_id`).
Original message: Mysql2::Error: Cannot add foreign key constraint: CREATE TABLE `journal_settings` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `value_changes` json NOT NULL, `user_id` bigint NOT NULL, `created_on` datetime NOT NULL,  INDEX `index_journal_settings_on_user_id`  (`user_id`), CONSTRAINT `fk_rails_63e8001bd8`
FOREIGN KEY (`user_id`)
  REFERENCES `users` (`id`)
)

**Comment by ashrafalzyoud** [comment]
when i change [4.2] its migrte
but give me this error
No such file to load -- organizations/memberships_controller.rb (LoadError)

**Comment by ashrafalzyoud** [comment]
@nanego

**Comment by ashrafalzyoud** [comment]
@nicolas-brousse

**Comment by ashrafalzyoud** [comment]
+

**Comment by ashrafalzyoud** [comment]
@nanego any answer plz i need your plugin

**Comment by ashrafalzyoud** [comment]
No such file to load -- organizations/memberships_controller.rb (LoadError)
still same error

**Comment by nanego** [comment]
Hello.
The "organizations/memberships_controller" file is only loaded when the "redmine_organizations" plugin is installed.
You may have modified the code of the plugin.
I'm closing this issue for now.

**Comment by ashrafalzyoud** [comment]
No such file to load -- organizations/memberships_controller.rb (LoadError)
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:378:in `block in require_or_load'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `load_interlock'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:356:in `require_or_load'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:334:in `depend_on'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:246:in `require_dependency'
  /home/redmine/redmine-4.222/plugins/redmine_admin_activity/lib/redmine_admin_activity/controllers/organizations/memberships_controller.rb:1:in `<top (required)>'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  /home/redmine/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'

how You may have modified the code of the plugin.
???

**Comment by ashrafalzyoud** [comment]
> Hello. The "organizations/memberships_controller" file is only loaded when the "redmine_organizations" plugin is installed. You may have modified the code of the plugin. I'm closing this issue for now.

what i do to modify it
