### ISSUE TITLE
 "redmine_organizations" 

### ISSUE THREAD

**Issue by ashrafalzyoud** [nanego/redmine_admin_activity#26]
this plugin work only when the "redmine_organizations" plugin is installed.
and the  "redmine_organizations" its failing in test
what i  can do

**Comment by nanego** [comment]
This plugin should work fine without the organization plugin.
These two plugins are made to work well together, but it's optional.

**Comment by whotopia** [comment]
In my case puma fails to start with error:

`
...../src/redmine-4.2.5/plugins/redmine_admin_activity/lib/redmine_admin_activity/controllers/organizations/memberships_controller.rb:1:in '<top (required)>'
.....

.....
from ..... .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'require'
.....rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'require': No such file to load -- organizations/memberships_controller.rb (LoadError)`

Is there's a way to get startup to ignore this error?     (Running Redmine 4.2.5 )
