### ISSUE TITLE
Error for install plugin

### ISSUE THREAD

**Issue by BocharnikovDmitry** [nanego/redmine_admin_activity#34]
Hi!
Installed our plugin, have any error (v2.2.5)

Column `user_id` on table `journal_settings` does not match column `id` on `users`, which has type `int(11)`. To resolve this issue, change the type of the `user_id` column on `journal_settings` to be :integer. (For example `t.integer :user_id`).
Original message: Mysql2::Error: Cannot add foreign key constraint: CREATE TABLE `journal_settings` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `value_changes` json NOT NULL, `user_id` bigint NOT NULL, `created_on` datetime NOT NULL,  INDEX `index_journal_settings_on_user_id`  (`user_id`), CONSTRAINT `fk_rails_63e8001bd8`
FOREIGN KEY (`user_id`)
  REFERENCES `users` (`id`)
)

...

Caused by:
ActiveRecord::MismatchedForeignKey: Column `user_id` on table `journal_settings` does not match column `id` on `users`, which has type `int(11)`. To resolve this issue, change the type of the `user_id` column on `journal_settings` to be :integer. (For example `t.integer :user_id`).
Original message: Mysql2::Error: Cannot add foreign key constraint: CREATE TABLE `journal_settings` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `value_changes` json NOT NULL, `user_id` bigint NOT NULL, `created_on` datetime NOT NULL,  INDEX `index_journal_settings_on_user_id`  (`user_id`), CONSTRAINT `fk_rails_63e8001bd8`
FOREIGN KEY (`user_id`)
  REFERENCES `users` (`id`)
)

**Comment by whotopia** [comment]
I have same issue.  (redmine version 4.2.5)

**Comment by nanego** [comment]
Hi
I have updated the migration file to specify the user_id column type. 
Please try the new version and confirm it works. We've never met this issue with PostgreSQL, it probably only occurs when using MySQL.

**Comment by nanego** [comment]
I close this issue as it should be resolved now.
